create table "public"."athletes" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "last_name" text,
  "first_name" text,
  "birthdate" date,
  "location" text,
  "avatar" text
);
alter table "public"."athletes" enable row level security;
CREATE UNIQUE INDEX athletes_pkey ON public.athletes USING btree (id);
alter table "public"."athletes"
add constraint "athletes_pkey" PRIMARY KEY using index "athletes_pkey";
grant delete on table "public"."athletes" to "anon";
grant insert on table "public"."athletes" to "anon";
grant references on table "public"."athletes" to "anon";
grant select on table "public"."athletes" to "anon";
grant trigger on table "public"."athletes" to "anon";
grant truncate on table "public"."athletes" to "anon";
grant update on table "public"."athletes" to "anon";
grant delete on table "public"."athletes" to "authenticated";
grant insert on table "public"."athletes" to "authenticated";
grant references on table "public"."athletes" to "authenticated";
grant select on table "public"."athletes" to "authenticated";
grant trigger on table "public"."athletes" to "authenticated";
grant truncate on table "public"."athletes" to "authenticated";
grant update on table "public"."athletes" to "authenticated";
grant delete on table "public"."athletes" to "service_role";
grant insert on table "public"."athletes" to "service_role";
grant references on table "public"."athletes" to "service_role";
grant select on table "public"."athletes" to "service_role";
grant trigger on table "public"."athletes" to "service_role";
grant truncate on table "public"."athletes" to "service_role";
grant update on table "public"."athletes" to "service_role";